name: tobac-dev
channels:
  - conda-forge
dependencies:
  - python>=3.9,<3.14
  - numpy
  - scipy
  - scikit-image
  - scikit-learn
  - pandas
  - matplotlib
  - iris
  - xarray
  - cartopy
  - trackpy
  - pytest
  - typing_extensions
  - black
  - coverage
  - pytest-cov
  - pylint
