name: tobac-dev
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - scikit-image
  - scikit-learn
  - pandas<3
  - matplotlib
  - iris
  - xarray<2024.10.0
  - cartopy
  - trackpy>=0.6.1
  - pytest
  - typing_extensions
  - black
  - jupyter
  - notebook
  - pytables
  - s3fs
  - arm_pyart
  - seaborn
  - h5netcdf
  - typing_extensions
  - rioxarray
  - numba
  - dask
  - ffmpeg
  - intake==0.7.0
  - intake-xarray==0.7.0
  - healpix
  - easygems
  - pyvista>=0.46
  - trame
  - trame-vtk
  - trame-vuetify
  - ipywidgets
  - vtk>=9.4.2
