name: Matrix Testing CI
# this is similar to the pyart CI action
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# This job installs dependencies and runs tests across a matrix of python and OS versions.
#Add if: github.repository == 'tobac-project/tobac' to limit runs to tobac repo

jobs:
  build:
    name: ${{ matrix.os }}-${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    if: github.repository == 'tobac-project/tobac'
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        os: [macos, ubuntu, windows]

    steps:
      - uses: actions/checkout@v2

      # Install micromamba and dependencies
      - name: Setup Conda Environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment-ci.yml
          activate-environment: pyart-dev
          cache-downloads: true
          channels: conda-forge
          channel-priority: strict
          python-version: ${{ matrix.python-version }}

      - name: Fetch all history for all tags and branches
        run: |
           git fetch --prune --unshallow

      - name: Install tobac
        shell: bash -l {0}
        run: |
          python -m pip install -e . --no-deps --force-reinstall

      - name: Run Tests
        id: run_tests
        shell: bash -l {0}
        run: |
          python -m pytest -v 
